Update queue zigzag to an array of usize. Add impl Bits for i64.
trueb2/tsz pull request #42
Opened 2023-12-01 18:53 UTC by ameykasbe

2023-12-01 21:59 UTC, trueb2 requested changes

2023-12-01 21:59 UTC, trueb2 commented on tsz-compress/src/v2/encode.rs
> +        word |= values[i] as u32;
It should be more efficient to build these up in the word as usize and cast once when creating the Full

2023-12-01 22:05 UTC, ameykasbe commented on tsz-compress/src/v2/encode.rs
> +        word |= values[i] as u32;
Updated in commit: [81d25c4](https://github.com/qsib-cbie/tsz/pull/42/commits/81d25c4ead8d2bb1e8d51630242731146b529a2c)

2023-12-03 15:39 UTC, trueb2 commented on tsz-compress/src/v2/encode.rs
> +    }
```suggestion
    #[inline(always)]
    fn zigzag_bits(self) -> (usize, usize) {
        let zbits = self.zigzag();
        (zbits, (usize::BITS - zbits.leading_zeros()) as usize)
    }
```

2023-12-03 15:55 UTC, merged